package com.orbisflow.common.errors;

public enum ApiErrorCode {
    INVALID_REQUEST,
    AUTH_REQUIRED,
    INVALID_CREDENTIALS,
    ACCESS_DENIED,
    CSRF_INVALID,
    INVALID_FILE,
    FILE_TOO_LARGE,
    UNSUPPORTED_MEDIA_TYPE,
    MANAGER_NOT_ASSIGNED,
    STATE_CONFLICT,
    VERSION_CONFLICT,
    SIGNED_LINK_INVALID,
    RESOURCE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    INTERNAL_ERROR
}
